// Global background listener: surfaces stock low / out-of-stock alerts as
// toasts (with a sound) to admins, managers, and staff who opted in via the
// `notify_stock` profile flag. The alerts themselves are generated by the
// `check_stock_alerts` DB trigger and land in the `notifications` table.
import { useEffect, useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { db } from "@/lib/db";
import { toast } from "sonner";
import { dingWaiterAlert } from "@/lib/kds";

type NotificationRow = {
  id: string;
  restaurant_id: string;
  type: string;
  level: string | null;
  title: string;
  body: string | null;
};

export function StockNotifier() {
  const { userId, profile, hasRole } = useAuth();
  const [eligible, setEligible] = useState(false);

  // Decide if this user should receive stock alerts.
  useEffect(() => {
    if (!userId) {
      setEligible(false);
      return;
    }
    if (hasRole("admin", "manager")) {
      setEligible(true);
      return;
    }
    let cancelled = false;
    db.from("profiles").select("notify_stock").eq("id", userId).maybeSingle()
      .then(({ data }: { data: { notify_stock: boolean } | null }) => {
        if (!cancelled) setEligible(!!data?.notify_stock);
      });
    return () => { cancelled = true; };
  }, [userId, hasRole]);

  useEffect(() => {
    if (!eligible || !profile?.restaurant_id) return;
    const ch = supabase
      .channel("stock-notify-" + (userId ?? "anon"))
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "notifications", filter: `restaurant_id=eq.${profile.restaurant_id}` },
        (payload) => {
          const n = payload.new as NotificationRow;
          dingWaiterAlert();
          const opts = { duration: 10000, description: n.body ?? undefined };
          if (n.level === "out") toast.error(n.title, opts);
          else toast.warning(n.title, opts);
        },
      )
      .subscribe();
    return () => {
      supabase.removeChannel(ch);
    };
  }, [eligible, profile?.restaurant_id, userId]);

  return null;
}
