/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWaitersRouteImport } from './routes/_authenticated/waiters'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTablesRouteImport } from './routes/_authenticated/tables'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedKdsRouteImport } from './routes/_authenticated/kds'
import { Route as AuthenticatedOrderSessionIdRouteImport } from './routes/_authenticated/order.$sessionId'
import { Route as AuthenticatedBillSessionIdRouteImport } from './routes/_authenticated/bill.$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWaitersRoute = AuthenticatedWaitersRouteImport.update({
  id: '/waiters',
  path: '/waiters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTablesRoute = AuthenticatedTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKdsRoute = AuthenticatedKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrderSessionIdRoute =
  AuthenticatedOrderSessionIdRouteImport.update({
    id: '/order/$sessionId',
    path: '/order/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillSessionIdRoute =
  AuthenticatedBillSessionIdRouteImport.update({
    id: '/bill/$sessionId',
    path: '/bill/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/more': typeof AuthenticatedMoreRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tables': typeof AuthenticatedTablesRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/waiters': typeof AuthenticatedWaitersRoute
  '/bill/$sessionId': typeof AuthenticatedBillSessionIdRoute
  '/order/$sessionId': typeof AuthenticatedOrderSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/more': typeof AuthenticatedMoreRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/tables': typeof AuthenticatedTablesRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/waiters': typeof AuthenticatedWaitersRoute
  '/bill/$sessionId': typeof AuthenticatedBillSessionIdRoute
  '/order/$sessionId': typeof AuthenticatedOrderSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/kds': typeof AuthenticatedKdsRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/tables': typeof AuthenticatedTablesRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/waiters': typeof AuthenticatedWaitersRoute
  '/_authenticated/bill/$sessionId': typeof AuthenticatedBillSessionIdRoute
  '/_authenticated/order/$sessionId': typeof AuthenticatedOrderSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kds'
    | '/menu'
    | '/more'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/tables'
    | '/vendors'
    | '/waiters'
    | '/bill/$sessionId'
    | '/order/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kds'
    | '/menu'
    | '/more'
    | '/reports'
    | '/settings'
    | '/stock'
    | '/tables'
    | '/vendors'
    | '/waiters'
    | '/bill/$sessionId'
    | '/order/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/kds'
    | '/_authenticated/menu'
    | '/_authenticated/more'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/tables'
    | '/_authenticated/vendors'
    | '/_authenticated/waiters'
    | '/_authenticated/bill/$sessionId'
    | '/_authenticated/order/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waiters': {
      id: '/_authenticated/waiters'
      path: '/waiters'
      fullPath: '/waiters'
      preLoaderRoute: typeof AuthenticatedWaitersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tables': {
      id: '/_authenticated/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof AuthenticatedTablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kds': {
      id: '/_authenticated/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AuthenticatedKdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order/$sessionId': {
      id: '/_authenticated/order/$sessionId'
      path: '/order/$sessionId'
      fullPath: '/order/$sessionId'
      preLoaderRoute: typeof AuthenticatedOrderSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bill/$sessionId': {
      id: '/_authenticated/bill/$sessionId'
      path: '/bill/$sessionId'
      fullPath: '/bill/$sessionId'
      preLoaderRoute: typeof AuthenticatedBillSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKdsRoute: typeof AuthenticatedKdsRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTablesRoute: typeof AuthenticatedTablesRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedWaitersRoute: typeof AuthenticatedWaitersRoute
  AuthenticatedBillSessionIdRoute: typeof AuthenticatedBillSessionIdRoute
  AuthenticatedOrderSessionIdRoute: typeof AuthenticatedOrderSessionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKdsRoute: AuthenticatedKdsRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTablesRoute: AuthenticatedTablesRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedWaitersRoute: AuthenticatedWaitersRoute,
  AuthenticatedBillSessionIdRoute: AuthenticatedBillSessionIdRoute,
  AuthenticatedOrderSessionIdRoute: AuthenticatedOrderSessionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
